services:
  - type: web
    name: eld-trip-planner-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: eld-trip-planner-db
          property: connectionString
      - key: NOMINATIM_USER_AGENT
        value: "eld-trip-planner/1.0"
      - key: OSRM_BASE_URL
        value: "https://router.project-osrm.org"
      - key: NOMINATIM_BASE_URL
        value: "https://nominatim.openstreetmap.org"

databases:
  - name: eld-trip-planner-db
    plan: free
