# Generated by Django 5.1.4 on 2026-06-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_coords', models.JSONField(blank=True, default=dict)),
                ('pickup_coords', models.JSONField(blank=True, default=dict)),
                ('dropoff_coords', models.JSONField(blank=True, default=dict)),
                ('total_distance_mi', models.FloatField(default=0)),
                ('total_duration_hrs', models.FloatField(default=0)),
                ('total_driving_hrs', models.FloatField(default=0)),
                ('total_on_duty_hrs', models.FloatField(default=0)),
                ('days_required', models.IntegerField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('kind', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('break', 'Break'), ('rest', 'Rest'), ('end', 'End')], max_length=16)),
                ('duty_status', models.CharField(choices=[('off', 'Off Duty'), ('sb', 'Sleeper Berth'), ('driving', 'Driving'), ('on', 'On Duty Not Driving')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('arrive_min', models.IntegerField()),
                ('depart_min', models.IntegerField()),
                ('miles_so_far', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['trip_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('start_location', models.CharField(blank=True, max_length=255)),
                ('end_location', models.CharField(blank=True, max_length=255)),
                ('miles_driven', models.FloatField(default=0)),
                ('totals', models.JSONField(default=dict)),
                ('segments', models.JSONField(default=list)),
                ('remarks', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['trip_id', 'day_index'],
            },
        ),
    ]
